alias ..='cd ..'
alias ls='ls --color=auto'
alias dir='ls'
alias ll='ls -l'
alias npp='/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe'
alias emacs='/c/emacs-23.4/bin/emacs.exe -nw'
alias subl='/c/Program\ Files/Sublime\ Text\ 2/sublime_text.exe'
alias gc='git commit'
alias gco='git checkout'
alias ga='git add'
alias gs='git status'
alias gap='git add -p'
alias gl='git lg'
alias gd='git diff'
alias less='less -FRXM'
alias clean='rm *~'
[[ -s $USERPROFILE/.pik/.pikrc ]] && source $USERPROFILE/.pik/.pikrc